# Generated by Django 5.1.5 on 2025-01-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdownfile',
            name='noteName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='markdownfile',
            name='htmlFile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
